-- 呼叫中心41张业务表，新库初始化；不包含FreeSWITCH自身运行表或旧测试数据。
-- 逻辑删除0/1；active_marker生成列使业务唯一键只约束有效记录。
-- 毫秒/秒计数和调度日期时间字符串保留，审计/注册时间使用datetime。

create table if not exists fs_media_server (
    `id` varchar(255)  NOT NULL COMMENT '主键id',
    `ip` varchar(50)  NOT NULL COMMENT 'IP',
    `ssl_status` tinyint  default 0 COMMENT '是否https',
    `hook_ip` varchar(50)  NOT NULL COMMENT 'hook使用的IP（zlm访问WVP使用的IP）',
    `sdp_ip` varchar(50)  NOT NULL COMMENT 'SDP IP',
    `stream_ip` varchar(50)  default null COMMENT '流IP',
    `http_port` int default 0 COMMENT 'HTTP端口',
    `http_ssl_port` int default 0 COMMENT 'HTTPS端口',
    `rtmp_port` int default 0 COMMENT 'RTMP端口',
    `rtmp_ssl_port` int default 0 COMMENT 'RTMPS端口',
    `rtp_proxy_port` int default 0 COMMENT 'RTP收流端口（单端口模式有用）',
    `rtsp_port` int default 0 COMMENT 'RTSP端口',
    `rtsp_ssl_port` int default 0 COMMENT 'RTSPS端口',
    `auto_config` tinyint default 1 COMMENT '是否开启自动配置ZLM',
    `secret` varchar(50)  default null COMMENT 'ZLM鉴权参数',
    `rtp_enable` tinyint default 0 COMMENT '是否使用多端口模式',
    `enable` tinyint default 0 COMMENT '启用状态',
    `keepalive_time` datetime  COMMENT '心跳时间',
    `status` tinyint default 0 COMMENT '状态',
    `rtp_port_range` varchar(50)  default null COMMENT '多端口RTP收流端口范围',
    `record_assist_port` int default 0 COMMENT 'assist服务端口',
    `default_server` tinyint default 0 COMMENT '是否是默认ZLM',
    `hook_alive_interval` int default 30 COMMENT 'keepalive hook触发间隔,单位秒',
    `video_play_prefix` varchar(50)  default null COMMENT '流媒体播放 代理前缀',
    `video_http_prefix` varchar(50)  default null COMMENT 'video请求时前缀',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_http_port (ip,http_port, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='流媒体服务信息';

create table if not exists fs_platform (
    `id` bigint not null COMMENT '主键id',
    `local_ip` varchar(30) DEFAULT null COMMENT '本机IP',
    `remote_ip` varchar(30) DEFAULT null COMMENT '外网IP',
    `internal_port` int DEFAULT '0' COMMENT '注册端口',
    `external_port` int DEFAULT '0' COMMENT '中继端口',
    `start_rtp_port` int DEFAULT '0' COMMENT '起始RTP端口',
    `end_rtp_port` int DEFAULT '0' COMMENT '结束RTP端口',
    `ws_port` int DEFAULT '0' COMMENT 'ws端口',
    `wss_port` int DEFAULT '0' COMMENT 'wss端口',
    `audio_code` varchar(256) DEFAULT '' COMMENT '音频编码',
    `video_code` varchar(256) DEFAULT '' COMMENT '视频编码',
    `frame_rate` varchar(30) DEFAULT '' COMMENT '分辨率',
    `bit_rate` varchar(30) DEFAULT '' COMMENT '码率',
    `ice_start` tinyint DEFAULT 1 COMMENT '是否启动ice',
    `stun_address` varchar(30) DEFAULT '' COMMENT 'stun地址',
    `name` varchar(255)  DEFAULT NULL COMMENT '名称',
    `enable` tinyint default 1 COMMENT '是否启用',
    `status` tinyint default 0 COMMENT '在线状态',
    `audio_record` tinyint DEFAULT 1 COMMENT '是否开启音频',
    `video_record` tinyint DEFAULT 1 COMMENT '是否开启视频',
    `audio_record_path` varchar(256) DEFAULT '' COMMENT '音频存储地址',
    `video_record_path` varchar(256) DEFAULT '' COMMENT '视频存储地址',
    `sound_rile_path` varchar(256) DEFAULT '' COMMENT '声音文件地址',
    `freeswitch_path` varchar(256) DEFAULT '' COMMENT '交换服务文件路径',
    `freeswitch_log_path` varchar(256) DEFAULT '' COMMENT '交换服务日志路径',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='平台信息';

create table if not exists fs_gate_way (
    `id` bigint not null COMMENT '主键id',
    `name` varchar(30) DEFAULT '' COMMENT '网关名称',
    `route_id` varchar(30) DEFAULT null COMMENT '关联路由id',
    `realm` varchar(30) DEFAULT null COMMENT '服务器地址',
    `register` int DEFAULT '0' COMMENT '是否注册',
    `transport` int DEFAULT '0' COMMENT '传输类型',
    `retry_seconds` int DEFAULT '0' COMMENT '重连间隔（秒）',
    `username` int DEFAULT '0' COMMENT '账户',
    `password` varchar(256) DEFAULT '' COMMENT '密码',
    `selected` varchar(256) DEFAULT '' COMMENT '是否选中0:未选中，1：已选中',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='网关中继信息';

create table if not exists fs_route_group (
    `id` bigint not null COMMENT '主键id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '网关组名称',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='网关组';

create table if not exists fs_route_gateway_group (
    `id` bigint not null COMMENT '主键id',
    `route_group_id` bigint NOT NULL DEFAULT '0' COMMENT '网关组',
    `gateway_id` bigint NOT NULL DEFAULT '0' COMMENT '媒体网关',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='路由与网关组关系表';

create table if not exists fs_route_gateway (
    `id` bigint not null COMMENT '主键id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '号码',
    `media_host` varchar(255)  NOT NULL DEFAULT '' COMMENT '媒体地址',
    `media_port` int NOT NULL DEFAULT '0' COMMENT '媒体端口',
    `caller_prefix` varchar(255)  NOT NULL DEFAULT '' COMMENT '主叫号码前缀',
    `called_prefix` varchar(255)  NOT NULL DEFAULT '' COMMENT '被叫号码前缀',
    `profile` varchar(255)  NOT NULL DEFAULT '' COMMENT 'fs的context规则',
    `sip_header1` varchar(255)  NOT NULL DEFAULT '' COMMENT 'sip头1',
    `sip_header2` varchar(255)  NOT NULL DEFAULT '' COMMENT 'sip头2',
    `sip_header3` varchar(255)  NOT NULL DEFAULT '' COMMENT 'sip头3',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_gateway_name (name, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='媒体网关表';

create table if not exists fs_route_call (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '所属企业',
    `route_group_id` bigint NOT NULL DEFAULT '0' COMMENT '所属网关组',
    `route_num` varchar(32)  NOT NULL DEFAULT '' COMMENT '字冠号码',
    `num_max` int NOT NULL DEFAULT '0' COMMENT '最长',
    `num_min` int NOT NULL DEFAULT '0' COMMENT '最短',
    `caller_change` int NOT NULL DEFAULT '0' COMMENT '主叫替换规则',
    `caller_change_num` varchar(32)  NOT NULL DEFAULT '' COMMENT '替换号码',
    `called_change` int NOT NULL DEFAULT '0' COMMENT '被叫替换规则',
    `called_change_num` varchar(32)  NOT NULL DEFAULT '' COMMENT '替换号码',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY unq_idx_route (company_id,route_num)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='字冠路由表';

create table if not exists fs_company (
    `id` bigint not null COMMENT '主键id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '名称',
    `company_code` varchar(255)  NOT NULL DEFAULT '' COMMENT '简称',
    `contact` varchar(255)  NOT NULL DEFAULT '' COMMENT '联系人',
    `phone` varchar(255)  NOT NULL DEFAULT '' COMMENT '电话',
    `balance` decimal(19,4) default 0.0000 comment '金额，精确小数',
    `bill_type` int NOT NULL DEFAULT '0' COMMENT '1:呼出计费,2:呼入计费,3:双向计费,0:全免费',
    `pay_type` int NOT NULL DEFAULT '0' COMMENT '0:预付费;1:后付费',
    `hidden_customer` int NOT NULL DEFAULT '0' COMMENT '隐藏客户号码(0:不隐藏;1:隐藏)',
    `secret_type` int NOT NULL DEFAULT '0' COMMENT '坐席密码等级',
    `secret_key` varchar(32)  NOT NULL DEFAULT '' COMMENT '验证秘钥',
    `ivr_limit` int NOT NULL DEFAULT '0' COMMENT 'IVR通道数',
    `agent_limit` int NOT NULL DEFAULT '0' COMMENT '开通坐席',
    `group_limit` int NOT NULL DEFAULT '0' COMMENT '开通技能组',
    `conference_limit` int NOT NULL DEFAULT '0' COMMENT '开通会议室上限',
    `group_agent_limit` int NOT NULL DEFAULT '0' COMMENT '单技能组中坐席上限',
    `record_storage` int NOT NULL DEFAULT '0' COMMENT '录音保留天数',
    `notify_url` varchar(255)  DEFAULT '' COMMENT '话单回调通知',
    `status` int NOT NULL DEFAULT '0' COMMENT '状态(0:禁用企业,1:免费企业;2:试用企业,3:付费企业)',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY company_name (name, active_marker),
    UNIQUE KEY company_code (company_code, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='企业信息表';

create table if not exists fs_company_conference (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '会议室名',
    `code` varchar(255)  NOT NULL DEFAULT '' COMMENT '会议室号码',
    `password` varchar(255)  NOT NULL DEFAULT '' COMMENT '会议室密码',
    `status` int NOT NULL DEFAULT '0' COMMENT '使用状态(1.未使用 1.使用中)',
    `enable` int NOT NULL DEFAULT '0' COMMENT '启用状态(0.禁用 1.启用)',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY company_name (name, active_marker),
    UNIQUE KEY company_code (code, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='企业会议室表';

create table if not exists fs_company_display (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '号码池',
    `type` int NOT NULL DEFAULT '0' COMMENT '1:呼入号码,2:主叫显号,3:被叫显号',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY idx_company_display (company_id,name)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='号码池表';

create table if not exists fs_company_phone_group (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `display_id` bigint NOT NULL DEFAULT '0' COMMENT '号码池id',
    `phone_id` bigint NOT NULL DEFAULT '0' COMMENT '号码id',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='企业号码与号码池中间表';

create table if not exists fs_company_phone (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `phone` varchar(255)  NOT NULL DEFAULT '' COMMENT '号码',
    `type` int NOT NULL DEFAULT '0' COMMENT '1:呼入号码,2:主叫显号,3:被叫显号',
    `status` int NOT NULL DEFAULT '1' COMMENT '1:未启用,2:启用',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_company_phone_phone (company_id,phone,type, active_marker),
    KEY idx_company_phone_company_id (company_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='企业号码';

create table if not exists fs_group (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `name` varchar(20)  NOT NULL DEFAULT '' COMMENT '技能组名称',
    `after_interval` int NOT NULL DEFAULT '5' COMMENT '话后自动空闲时长',
    `caller_display_id` bigint NOT NULL DEFAULT '0' COMMENT '主叫显号号码池',
    `called_display_id` bigint NOT NULL DEFAULT '0' COMMENT '被叫显号号码池',
    `record_type` int NOT NULL DEFAULT '1' COMMENT '1:振铃录音,2:接通录音',
    `level_value` int NOT NULL DEFAULT '1' COMMENT '技能组优先级',
    `tts_engine` bigint NOT NULL DEFAULT '0' COMMENT 'tts引擎id',
    `play_content` varchar(100)  NOT NULL DEFAULT '' COMMENT '转坐席时播放内容',
    `evaluate` bigint NOT NULL DEFAULT '0' COMMENT '转服务评价(0:否,1:是)',
    `queue_play` bigint NOT NULL DEFAULT '0' COMMENT '排队音',
    `transfer_play` bigint NOT NULL DEFAULT '0' COMMENT '转接提示音',
    `call_time_out` int NOT NULL DEFAULT '30' COMMENT '外呼呼叫超时时间',
    `group_type` int NOT NULL DEFAULT '0' COMMENT '技能组类型',
    `notify_position` int NOT NULL DEFAULT '0' COMMENT '0:不播放排队位置,1:播放排队位置',
    `notify_rate` int NOT NULL DEFAULT '10' COMMENT '频次',
    `notify_content` varchar(255)  NOT NULL DEFAULT '' COMMENT '您前面还有$位用户在等待',
    `call_memory` int NOT NULL DEFAULT '1' COMMENT '主叫记忆(1:开启,0:不开启)',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_company_name (company_id,name, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能组表';

create table if not exists fs_group_agent_strategy (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组id',
    `strategy_type` int NOT NULL DEFAULT '1' COMMENT '1:内置策略,2:自定义',
    `strategy_value` int NOT NULL DEFAULT '1' COMMENT '(策略值 1当前最长空闲时间、2空闲次数最多、3最少应答次数、4累计最少通话时长、5累计话后时长、6轮选、7随机)',
    `custom_expression` varchar(255)  NOT NULL DEFAULT '' COMMENT '自定义表达式',
    `status` int NOT NULL DEFAULT '1',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能组中坐席分配策略';

create table if not exists fs_group_strategy_exp (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组id',
    `strategy_key` varchar(20)  NOT NULL DEFAULT '' COMMENT '自定义值',
    `strategy_present` int NOT NULL DEFAULT '1' COMMENT '百分百',
    `strategy_type` int NOT NULL DEFAULT '1' COMMENT '类型',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能组坐席自定义策略表';

create table if not exists fs_group_memory_config (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组ID',
    `success_strategy` int NOT NULL DEFAULT '0' COMMENT '匹配成功策略 1:等待记忆坐席 2:超时转其他空闲坐席 3:忙碌转空闲坐席',
    `success_strategy_value` bigint NOT NULL DEFAULT '0' COMMENT '匹配成功策略值（暂未用到）',
    `fail_strategy` int NOT NULL DEFAULT '0' COMMENT '匹配失败策略 1:其他空闲坐席 2:其他技能组 3:vdn 4:ivr 5:挂机',
    `fail_strategy_value` bigint NOT NULL DEFAULT '0' COMMENT '匹配失败策略值（所处编号值）',
    `memory_day` int NOT NULL DEFAULT '30' COMMENT '记忆天数',
    `inbound_cover` int NOT NULL DEFAULT '0' COMMENT '呼入覆盖',
    `outbound_cover` int NOT NULL DEFAULT '0' COMMENT '外呼覆盖',
    `status` int NOT NULL DEFAULT '1',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_group (group_id, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能组坐席记忆配置表';

create table if not exists fs_group_overflow (
    `id` bigint not null COMMENT '主键id',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组ID',
    `overflow_id` bigint NOT NULL DEFAULT '0' COMMENT '溢出策略ID',
    `level_value` int NOT NULL DEFAULT '1' COMMENT '优先级',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_group_overflow (group_id,overflow_id, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能组排队策略表';

create table if not exists fs_skill (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '名称',
    `remark` varchar(255)  NOT NULL DEFAULT '' COMMENT '备注',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_skill_name (company_id,name, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能表';

create table if not exists fs_skill_agent (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `skill_id` bigint NOT NULL DEFAULT '0' COMMENT '技能id',
    `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席id',
    `rank_value` int NOT NULL DEFAULT '0' COMMENT '范围',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='坐席技能表';

create table if not exists fs_skill_group (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `level_value` int NOT NULL DEFAULT '1',
    `skill_id` bigint NOT NULL DEFAULT '0' COMMENT '技能ID',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组ID',
    `rank_type` tinyint not null DEFAULT '1' COMMENT '等级类型(1:全部,2:等于,3:>,4:<,5:介于)',
    `rank_value_start` int NOT NULL DEFAULT '0' COMMENT '介于的开始值',
    `rank_value` int NOT NULL DEFAULT '1' COMMENT '等级值 技能等级在0-100之间',
    `match_type` int NOT NULL DEFAULT '1' COMMENT '匹配规则(1:低到高,2:高到低)',
    `share_value` int NOT NULL DEFAULT '100' COMMENT '占用率 (占用率在1-100之间)',
    `status` tinyint not null DEFAULT '0' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY idx_group_id (group_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='技能组技能表';

create table if not exists fs_agent (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `agent_id` varchar(255)  NOT NULL DEFAULT '' COMMENT '坐席工号',
    `agent_key` varchar(255)  NOT NULL DEFAULT '' COMMENT '坐席账户',
    `agent_name` varchar(255)  NOT NULL DEFAULT '' COMMENT '坐席名称',
    `agent_code` varchar(20)  NOT NULL DEFAULT '' COMMENT '坐席分机号',
    `agent_type` int NOT NULL DEFAULT '2' COMMENT '座席类型：1:普通座席；2：班长',
    `passwd` varchar(255)  NOT NULL DEFAULT '' COMMENT '座席密码',
    `record` int NOT NULL DEFAULT '0' COMMENT '是否录音 0 no 1 yes',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '座席主要技能组  不能为空 必填项',
    `after_interval` int NOT NULL DEFAULT '5' COMMENT '话后自动空闲间隔时长',
    `display` varchar(255)  NOT NULL DEFAULT '' COMMENT '主叫显号',
    `ring_time` int NOT NULL DEFAULT '10' COMMENT '振铃时长',
    `host` varchar(255)  NOT NULL DEFAULT '0.0.0.0' COMMENT '登录服务器地址',
    `state` int NOT NULL DEFAULT '0' COMMENT '坐席状态(1:在线,0:不在线)',
    `status` int NOT NULL DEFAULT '1' COMMENT '状态：1 开通，0关闭',
    `register_time` datetime  DEFAULT NULL COMMENT '注册时间',
    `renew_time` datetime  DEFAULT NULL COMMENT '续订时间',
    `keepalive_time` datetime  DEFAULT NULL COMMENT '心跳时间',
    `keep_timeout` int default 30 COMMENT '心跳间隔 (最低25秒)',
    `expires` int DEFAULT 86400 COMMENT '注册有效期（单位：秒 默认1天）',
    `stream_mode` tinyint  DEFAULT 0 COMMENT '数据流传输模式 0.UDP:udp传输 1.TCP-PASSIVE：tcp被动模式 2.TCP-ACTIVE：tcp主动模式',
    `transport` tinyint  DEFAULT NULL COMMENT '传输协议 1.UDP 2.TCP',
    `charset` tinyint  default 1 COMMENT '字符集, 1.UTF-8 2.GB2312',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_key (agent_key, active_marker),
    UNIQUE KEY idx_agent_code_company (agent_code,company_id, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='座席工号表';

create table if not exists fs_user_agent (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `agent_id` bigint not null comment '关联数据库雪花ID',
    `user_id` bigint not null comment '关联数据库雪花ID',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY idx_user_agent_company_user (company_id, user_id, del_flag)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='用户座席中间表';

create table if not exists fs_agent_group (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席id',
    `agent_key` varchar(50)  NOT NULL DEFAULT '' COMMENT '坐席key',
    `agent_type` int NOT NULL DEFAULT '1' COMMENT '坐席类型 1.普通员工 2.组长',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组id',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_group_agent_group (group_id,agent_id, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='坐席技能组表';

create table if not exists fs_agent_sip (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint DEFAULT '0' COMMENT '企业主键',
    `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席主键',
    `sip` varchar(32)  NOT NULL DEFAULT '' COMMENT 'sip编号',
    `sip_pwd` varchar(255)  DEFAULT '' COMMENT 'sip密码',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    KEY idx_agent_sip_agent (agent_id),
    UNIQUE KEY idx_sip (sip, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='sip表';

create table if not exists fs_agent_state_log (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '主技能组id',
    `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席id',
    `agent_key` varchar(255)  NOT NULL DEFAULT '' COMMENT '坐席编号',
    `agent_name` varchar(255)  NOT NULL DEFAULT '' COMMENT '坐席名称',
    `call_id` bigint NOT NULL DEFAULT '0' COMMENT '通话唯一标识',
    `login_type` int NOT NULL DEFAULT '1' COMMENT '登录类型',
    `work_type` int NOT NULL DEFAULT '1' COMMENT '工作类型',
    `host` varchar(255)  NOT NULL DEFAULT '' COMMENT '服务站点',
    `remote_address` varchar(255)  NOT NULL DEFAULT '' COMMENT '远端地址',
    `before_state` varchar(50)  NOT NULL DEFAULT '' COMMENT '变更之前状态',
    `before_time` bigint NOT NULL DEFAULT '0' COMMENT '更变之前时间',
    `state` varchar(50)  NOT NULL DEFAULT '' COMMENT '变更之后状态',
    `state_time` bigint NOT NULL DEFAULT '0' COMMENT '当前时间(秒)',
    `duration` int NOT NULL DEFAULT '0' COMMENT '持续时间(秒)',
    `busy_desc` varchar(255)  NOT NULL DEFAULT '' COMMENT '忙碌类型',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY idx_agent_state_agent_key (agent_key),
    KEY idx_agent_state_cts (state_time),
    KEY idx_agent_state_group_id (group_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='坐席状态历史表';

create table if not exists fs_call_detail (
    `id` bigint not null COMMENT '主键id',
    `start_time` bigint NOT NULL DEFAULT '0' COMMENT '开始时间',
    `end_time` bigint NOT NULL DEFAULT '0' COMMENT '结束时间',
    `call_id` bigint NOT NULL DEFAULT '0' COMMENT '通话ID',
    `detail_index` int NOT NULL DEFAULT '1' COMMENT '顺序',
    `transfer_type` int NOT NULL DEFAULT '0' COMMENT '1:进vdn,2:进ivr,3:技能组,4:按键收号,5:外线,6:机器人,10:服务评价',
    `transfer_id` bigint NOT NULL DEFAULT '0' COMMENT '转接ID',
    `reason` varchar(50)  NOT NULL DEFAULT '' COMMENT '出队列原因:排队挂机或者转坐席',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY idx_call_detail_call_id (call_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='通话流程表';

create table if not exists fs_call_device (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `call_id` bigint NOT NULL DEFAULT '0' COMMENT '通话ID',
    `device_id` varchar(50)  NOT NULL DEFAULT '' COMMENT '设备id',
    `agent_key` varchar(50)  NOT NULL DEFAULT '' COMMENT '坐席',
    `agent_name` varchar(50)  NOT NULL DEFAULT '' COMMENT '坐席名称',
    `device_type` int NOT NULL DEFAULT '1' COMMENT '1:坐席,2:客户,3:外线',
    `cdr_type` int NOT NULL DEFAULT '1' COMMENT '1:呼入,2:外呼,3:内呼,4:转接,5:咨询,6:监听,7:强插',
    `from_agent` varchar(50)  NOT NULL DEFAULT '' COMMENT '转接或咨询发起者',
    `caller` varchar(50)  NOT NULL DEFAULT '' COMMENT '主叫',
    `called` varchar(50)  NOT NULL DEFAULT '' COMMENT '被叫',
    `display` varchar(50)  NOT NULL DEFAULT '' COMMENT '显号',
    `called_location` varchar(100)  NOT NULL DEFAULT '' COMMENT '被叫归属地',
    `caller_location` varchar(100)  NOT NULL DEFAULT '' COMMENT '被叫归属地',
    `call_time` bigint NOT NULL DEFAULT '0' COMMENT '呼叫开始时间',
    `ring_start_time` bigint NOT NULL DEFAULT '0' COMMENT '振铃开始时间',
    `ring_end_time` bigint NOT NULL DEFAULT '0' COMMENT '振铃结束时间',
    `answer_time` bigint NOT NULL DEFAULT '0' COMMENT '接通时间',
    `bridge_time` bigint NOT NULL DEFAULT '0' COMMENT '桥接时间',
    `end_time` bigint NOT NULL DEFAULT '0' COMMENT '结束时间',
    `talk_time` bigint NOT NULL DEFAULT '0' COMMENT '通话时长',
    `record_start_time` bigint NOT NULL DEFAULT '0' COMMENT '录音开始时间',
    `record_time` bigint NOT NULL DEFAULT '0' COMMENT '录音时长',
    `sip_protocol` varchar(50)  NOT NULL DEFAULT '' COMMENT '信令协议(tcp/udp)',
    `record` varchar(255)  NOT NULL DEFAULT '' COMMENT '录音地址',
    `record2` varchar(255)  NOT NULL DEFAULT '' COMMENT '备用录音地址',
    `record3` varchar(255)  NOT NULL DEFAULT '' COMMENT '备用录音地址',
    `channel_name` varchar(50)  NOT NULL DEFAULT '' COMMENT '呼叫地址',
    `hangup_cause` varchar(50)  NOT NULL COMMENT '挂机原因',
    `ring_cause` varchar(50)  NOT NULL DEFAULT '' COMMENT '回铃音识别',
    `sip_status` varchar(50)  NOT NULL DEFAULT '' COMMENT 'sip状态',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id),
    KEY idx_call_detail_call_id (call_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='话单明细表';

create table if not exists fs_call_dtmf (
    `id` bigint not null COMMENT '主键id',
    `dtmf_key` varchar(255)  NOT NULL DEFAULT '' COMMENT '按键号码',
    `process_id` bigint NOT NULL DEFAULT '0' COMMENT '业务流程id',
    `call_id` bigint NOT NULL DEFAULT '0' COMMENT '通话标识id',
    `dtmf_time` bigint NOT NULL DEFAULT '0' COMMENT '按键时间',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='呼叫按键表';

create table if not exists fs_call_log (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `call_id` bigint NOT NULL DEFAULT '0' COMMENT '话单id',
    `caller_display` varchar(100)  NOT NULL DEFAULT '' COMMENT '主叫显号',
    `caller` varchar(100)  NOT NULL DEFAULT '' COMMENT '主叫',
    `called_display` varchar(100)  NOT NULL DEFAULT '' COMMENT '被叫显号',
    `called` varchar(100)  NOT NULL DEFAULT '' COMMENT '被叫',
    `number_location` varchar(100)  NOT NULL DEFAULT '' COMMENT '客户号码归属地',
    `agent_key` varchar(50)  NOT NULL DEFAULT '' COMMENT '坐席',
    `agent_name` varchar(255)  NOT NULL DEFAULT '' COMMENT '坐席名称',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组',
    `login_type` int NOT NULL DEFAULT '1' COMMENT '1:sip号,2:webrtc,3:手机',
    `task_id` bigint NOT NULL DEFAULT '0' COMMENT '任务ID',
    `ivr_id` bigint NOT NULL DEFAULT '0' COMMENT 'ivr',
    `bot_id` bigint NOT NULL DEFAULT '0' COMMENT '机器人id',
    `call_time` bigint NOT NULL DEFAULT '0' COMMENT '呼叫开始时间',
    `answer_time` bigint NOT NULL DEFAULT '0' COMMENT '接听时间',
    `end_time` bigint NOT NULL DEFAULT '0' COMMENT '结束时间',
    `call_type` varchar(32)  NOT NULL DEFAULT '' COMMENT '呼叫类型',
    `direction` varchar(32)  NOT NULL DEFAULT '' COMMENT '呼叫方向',
    `answer_flag` int NOT NULL DEFAULT '0' COMMENT '通话标识(0:接通,1:坐席未接用户未接,2:坐席接通用户未接通,3:用户接通坐席未接通)',
    `wait_time` bigint NOT NULL DEFAULT '0' COMMENT '累计等待时长',
    `answer_count` int NOT NULL DEFAULT '0' COMMENT '应答设备数',
    `hangup_dir` int NOT NULL DEFAULT '1' COMMENT '挂机方向(1:主叫挂机,2:被叫挂机,3:系统挂机)',
    `sdk_hangup` int NOT NULL DEFAULT '0' COMMENT '是否sdk挂机(1:sdk挂机)',
    `hangup_code` int NOT NULL DEFAULT '0' COMMENT '挂机原因',
    `media_host` varchar(255)  NOT NULL DEFAULT '' COMMENT '媒体服务器',
    `cti_host` varchar(255)  NOT NULL DEFAULT '' COMMENT 'cti地址',
    `client_host` varchar(255)  NOT NULL DEFAULT '' COMMENT '客户端地址',
    `record` varchar(255)  NOT NULL DEFAULT '' COMMENT '录音地址',
    `record2` varchar(255)  NOT NULL DEFAULT '' COMMENT '备用录音地址',
    `record3` varchar(255)  NOT NULL DEFAULT '' COMMENT '备用录音地址',
    `record_type` int NOT NULL DEFAULT '1' COMMENT '录音状态',
    `record_start_time` bigint NOT NULL DEFAULT '0' COMMENT '录音开始时间',
    `record_time` bigint NOT NULL DEFAULT '0' COMMENT '录音时间',
    `talk_time` bigint NOT NULL DEFAULT '0' COMMENT '通话时长',
    `frist_queue_time` bigint NOT NULL DEFAULT '0' COMMENT '第一次进队列时间',
    `queue_start_time` bigint NOT NULL DEFAULT '0' COMMENT '进队列时间',
    `queue_end_time` bigint NOT NULL DEFAULT '0' COMMENT '出队列时间',
    `month_time` varchar(50)  NOT NULL DEFAULT '' COMMENT '月份',
    `follow_data` varchar(4096)  NOT NULL DEFAULT '' COMMENT '通话随路数据(2048)',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_call_log_call_id (call_id, active_marker),
    KEY idx_call_log_agent (agent_key),
    KEY idx_call_log_group (group_id),
    KEY idx_call_log_create_time (company_id,call_time)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='话单表';

create table if not exists fs_group_memory (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `group_id` bigint NOT NULL DEFAULT '0' COMMENT '技能组ID',
    `agent_key` varchar(32)  NOT NULL DEFAULT '' COMMENT '坐席',
    `phone` varchar(255)  NOT NULL DEFAULT '' COMMENT '客户电话',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY idx_group_id (group_id,phone,agent_key, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='坐席与客户记忆表';

create table if not exists fs_ivr_workflow (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '流程名称',
    `oss_id` varchar(255)  NOT NULL DEFAULT '' COMMENT '流程文件名',
    `init_params` text  COMMENT '用来存贮 ivr 流程启动所需要的参数描述',
    `create_user` varchar(255)  NOT NULL DEFAULT '' COMMENT '流程发布人',
    `verify_user` varchar(255)  NOT NULL DEFAULT '' COMMENT '流程审核人',
    `content` text  COMMENT '流程内容(ivr)',
    `voice_item` varchar(10000)  NOT NULL DEFAULT '' COMMENT '该流程用到的语音文件id，以英文逗号,分隔',
    `type` int NOT NULL DEFAULT '1' COMMENT '1转接，2咨询',
    `status` int NOT NULL COMMENT '流程状态    1：待发布   2：审核中  3：审核未通过  4：审核通过  5：已上线(ivr)',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='ivr流程表';

create table if not exists fs_overflow_config (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint DEFAULT '0' COMMENT '企业id',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT '名称',
    `handle_type` int NOT NULL DEFAULT '1' COMMENT '1:排队,2:溢出,3:挂机',
    `busy_type` int DEFAULT '1' COMMENT '排队方式(1:先进先出,2:vip,3:自定义)',
    `queue_timeout` int DEFAULT '60' COMMENT '排队超时时间',
    `busy_timeout_type` int DEFAULT '1' COMMENT '排队超时(1:溢出,2:挂机)',
    `overflow_type` int DEFAULT '1' COMMENT '溢出(1:group,2:ivr,3:vdn)',
    `overflow_value` bigint default 0 comment '溢出目标雪花ID',
    `lineup_expression` varchar(255)  DEFAULT '' COMMENT '自定义排队表达式',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY uni_idx_name (company_id,name, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='溢出策略表';

create table if not exists fs_overflow_exp (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `overflow_id` bigint NOT NULL DEFAULT '0' COMMENT '溢出策略ID',
    `exp_key` varchar(30)  NOT NULL DEFAULT '' COMMENT '自定义值',
    `rate` int NOT NULL DEFAULT '1' COMMENT '权重',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='自定义溢出策略优先级';

create table if not exists fs_overflow_front (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `overflow_id` bigint NOT NULL DEFAULT '0' COMMENT '策略ID',
    `front_type` int NOT NULL DEFAULT '1' COMMENT '1:队列长度; 2:队列等待最大时长; 3:呼损率',
    `compare_condition` int NOT NULL DEFAULT '0' COMMENT '0:全部; 1:小于或等于; 2:等于; 3:大于或等于; 4:大于 ;5.介于',
    `rank_value_start` int NOT NULL DEFAULT '0' COMMENT '介于的开始值',
    `rank_value` int NOT NULL DEFAULT '0' COMMENT '符号条件值',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='溢出策略前置条件';

create table if not exists fs_playback (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL COMMENT '企业ID',
    `playback` varchar(255)  NOT NULL DEFAULT '' COMMENT '放音文件',
    `status` int NOT NULL DEFAULT '1' COMMENT '1:待审核,2:审核通过',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='语音文件表';

create table if not exists fs_push_log (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业id',
    `call_id` bigint NOT NULL DEFAULT '0' COMMENT 'callid',
    `cdr_notify_url` varchar(255)  NOT NULL DEFAULT '' COMMENT '发送次数',
    `content` varchar(10240)  NOT NULL DEFAULT '' COMMENT '推送内容',
    `push_times` int NOT NULL DEFAULT '1' COMMENT '推送次数',
    `push_response` varchar(255)  NOT NULL DEFAULT '' COMMENT '推送返回值',
    `status` int NOT NULL DEFAULT '1' COMMENT '状态(1:推送，0:不推送)',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='话单推送记录表';

create table if not exists fs_vdn_schedule (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL  COMMENT '企业ID',
    `name` varchar(20) DEFAULT '' COMMENT '日程名称',
    `level_value` int NOT NULL DEFAULT '1' COMMENT '优先级',
    `type` int NOT NULL DEFAULT '1' COMMENT '1:指定时间,2:相对时间',
    `start_day` varchar(50) DEFAULT '' COMMENT '开始时间',
    `end_day` varchar(50) DEFAULT '' COMMENT '结束时间',
    `start_time` varchar(50) DEFAULT '' COMMENT '开始时间',
    `end_time` varchar(50) DEFAULT '' COMMENT '结束时间',
    `mon` int NOT NULL DEFAULT '1' COMMENT '周一',
    `tue` int NOT NULL DEFAULT '1' COMMENT '周二',
    `wed` int NOT NULL DEFAULT '1' COMMENT '周三',
    `thu` int NOT NULL DEFAULT '1' COMMENT '周四',
    `fri` int NOT NULL DEFAULT '1' COMMENT '周五',
    `sat` int NOT NULL DEFAULT '1' COMMENT '周六',
    `sun` int NOT NULL DEFAULT '1' COMMENT '周天',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='日程表';

create table if not exists fs_vdn_code (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `name` varchar(255)  NOT NULL DEFAULT '' COMMENT 'vdn名称',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='呼入路由表';

create table if not exists fs_vdn_phone (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `vdn_id` bigint NOT NULL DEFAULT '0' COMMENT '路由码',
    `phone` varchar(20) NOT NULL DEFAULT '' COMMENT '特服号',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    `active_marker` tinyint generated always as (case when del_flag = '0' then 1 else null end) stored,
    PRIMARY KEY (id),
    UNIQUE KEY uni_idx_phone (vdn_id,company_id, active_marker)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='路由号码表';

create table if not exists fs_vdn_config (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `vdn_id` bigint NOT NULL DEFAULT '0' COMMENT '呼入路由编号',
    `schedule_id` bigint NOT NULL DEFAULT '0' COMMENT '日程id',
    `name` varchar(255) NOT NULL DEFAULT '' COMMENT '子码日程',
    `route_type` tinyint not null DEFAULT '1' COMMENT '路由类型(1:技能组,2:放音,3:ivr,4:坐席,5:外呼)',
    `route_value` varchar(255) NOT NULL DEFAULT '0' COMMENT '路由类型值',
    `play_type` tinyint not null DEFAULT '0' COMMENT '放音类型(1:按键导航,2:技能组,3:ivr,4:路由字码,5:挂机)',
    `play_value` bigint NOT NULL DEFAULT '0' COMMENT '放音类型对应值',
    `dtmf_end` varchar(255) NOT NULL DEFAULT '*' COMMENT '结束音',
    `retry` int NOT NULL DEFAULT '1' COMMENT '重复播放次数',
    `dtmf_max` int NOT NULL DEFAULT '1' COMMENT '最大收键长度',
    `dtmf_min` int NOT NULL DEFAULT '1' COMMENT '最小收键长度',
    `status` int NOT NULL DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='呼入路由字码表';

create table if not exists fs_vdn_dtmf (
    `id` bigint not null COMMENT '主键id',
    `company_id` bigint NOT NULL DEFAULT '0' COMMENT '企业ID',
    `navigate_id` bigint NOT NULL DEFAULT '0' COMMENT '呼入路由字码ID',
    `dtmf` varchar(20) NOT NULL DEFAULT '1' COMMENT '按键',
    `route_type` tinyint not null DEFAULT '0' COMMENT '路由类型(1:技能组,2:IVR,3:路由字码,4:坐席分机,5:挂机)',
    `route_value` bigint NOT NULL DEFAULT '0' COMMENT '路由值',
    `status` tinyint not null DEFAULT '1' COMMENT '状态',
    `create_dept` bigint default null comment '创建部门',
    `create_by` bigint default null comment '创建者',
    `create_time` datetime default null comment '创建时间',
    `update_by` bigint default null comment '更新者',
    `update_time` datetime default null comment '更新时间',
    `del_flag` char(1) not null default '0' comment '0存在1删除',
    PRIMARY KEY (id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_cs_0900_ai_ci row_format=dynamic comment='路由按键导航表';
