<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.com.nla</groupId>
        <artifactId>nla-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>nla-system</artifactId>

    <description>
        system系统模块
    </description>

    <dependencies>
        <!-- 通用工具-->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-core</artifactId>
        </dependency>

        <!-- api模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-api</artifactId>
        </dependency>

        <!-- 接口模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-doc</artifactId>
        </dependency>

        <!-- 数据库服务 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-mybatis</artifactId>
        </dependency>

        <!-- 翻译模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-translation</artifactId>
        </dependency>

        <!-- OSS功能模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-oss</artifactId>
        </dependency>

        <!-- 日志记录 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-log</artifactId>
        </dependency>

        <!-- excel-->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-excel</artifactId>
        </dependency>

        <!-- SMS功能模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-sms</artifactId>
        </dependency>

        <!-- 安全模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-security</artifactId>
        </dependency>

        <!-- web服务 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-web</artifactId>
        </dependency>

        <!-- 脱敏模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-sensitive</artifactId>
        </dependency>

        <!-- 数据库加解密模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-encrypt</artifactId>
        </dependency>

        <!-- 消息推送模块 -->
        <dependency>
            <groupId>cn.com.nla</groupId>
            <artifactId>nla-common-push</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
            <testResource>
                <directory>${project.basedir}/../../script/sql</directory>
                <includes><include>nla_system.sql</include></includes>
                <filtering>false</filtering>
            </testResource>
        </testResources>
    </build>

</project>
